### ISSUE TITLE
label propagation

### ISSUE THREAD

**Issue by Denisesabac** [BRANCHlab/metasnf#12]
Which version of meta snf has the lp_solutions_matrix function?

**Comment by pvelayudhan** [comment]
Hello,

in v0.4.1, the function `lp_row` was replaced by `lp_solutions_matrix`.

Results in the newer function should be identical.

Both functions require a "full data list" (one that has data for both the labeled and unlabeled subjects) as well as a solutions matrix (built only from the original labeled subjects). The only difference  is that `lp_row` was very picky about how subjects were ordered in the full data list, while the newer `lp_solutions_matrix` doesn't care. It will assume that anybody in the solutions matrix is part of the training/derivation/known label group and anybody that is unique to the data list is part of the test/validation/unknown label group.

In general I try to record any changes to the code in a changelog on the website, found here: https://branchlab.github.io/metasnf/news/index.html
