### ISSUE TITLE
installing metasnf

### ISSUE THREAD

**Issue by dsabac** [BRANCHlab/metasnf#5]
To all new users: make sure you are using the correct version of R and have all the required package updates to properly install metasnf. 

I got the following error when I initially tried to install metasnf: 
"Error in loadnamesspace(i, c(lib.loc, .libPaths()), versionCheck = vI [[i]]) : namespace 'rlang' 1.0.6 is already loaded, but >=1.1.1 is required"

**Comment by pvelayudhan** [comment]
Did this error end up going away after updating your packages?

This specific issue may be resolved with:

```
remove.packages("rlang")
install.packages("rlang")
```

From https://stackoverflow.com/a/73902678/16626788

**Comment by dsabac** [comment]
I downloaded the most recent version of R, version 4.3.1, with the updated rlang package and had no problem installing metasnf afterwards.
