### ISSUE TITLE
statistical tests in extend_solutions function

### ISSUE THREAD

**Issue by Denisesabac** [BRANCHlab/metasnf#7]
Hi! I am having some trouble replicating the p values calculated using the extend_solutions function. I am wondering what association tests are used to calculate the p values in this function, for each data type. Thank you!

**Comment by pvelayudhan** [comment]
`extend_solutions` is a wrapper for another function in R/solutions_matrix.R, `get_cluster_pval`. You can see the source for the function here: https://github.com/BRANCHlab/metasnf/blob/7d89bbe23e34999e733dee66734a83afba9a1c05/R/solutions_matrix.R#L241

The function calculates p-values one feature at a time for every feature in the outcome_list. Depending on what variable type was specified during outcome_list generation, the following tests would be used:

- ordinal: ordinal regression
- discrete, continuous, or the discontinued term "numeric": linear regression
- categorical: chi-squared test

The `extend_solutions` function also has a specific "cat_test" parameter where you can change the chi-squared test to be fisher exact. 

Within `get_cluster_pval` you can see the names of the functions that are being called to do the actual statistical test. I'll paste the source below for reference:

Linear model:

```
linear_model_pval <- function(predictor, response) {
    model <- stats::lm(response ~ predictor)
    fstat <- summary(model)$"fstatistic"
    pval <- stats::pf(fstat[1], fstat[2], fstat[3], lower.tail = FALSE)
    attributes(pval) <- NULL
    return(pval)
}
```

Ordinal regression:

```
ord_reg_pval <- function(predictor, response) {
    # If there are only 2 tiers to the ordinal scale, just use linear model
    num_classes <- length(unique(response))
    if (num_classes == 2) {
        return(linear_model_pval(predictor, response))
    }
    # Otherwise, run regular ordinal regression
    response <- as.ordered(response)
    null_model <- MASS::polr(response ~ 1)
    full_model <- MASS::polr(response ~ predictor)
    pval <- stats::anova(null_model, full_model)$"Pr(Chi)"[2]
    return(pval)
}
```

Chi-squared test:

```
chi_squared_pval <- function(cat_var1, cat_var2) {
    cat_var1 <- factor(cat_var1)
    cat_var2 <- factor(cat_var2)
    model <- stats::chisq.test(cat_var1, cat_var2, correct = FALSE)
    pval <- model$"p.value"
    attributes(pval) <- NULL
    return(pval)
}
```

Fisher exact:

```
fisher_exact_pval <- function(cat_var1, cat_var2) {
    cat_var1 <- factor(cat_var1)
    cat_var2 <- factor(cat_var2)
    model <- stats::fisher.test(cat_var1, cat_var2, workspace=2e7)
    pval <- model$"p.value"
    attributes(pval) <- NULL
    return(pval)
}
```

Let me know if you have any additional questions!

**Comment by Denisesabac** [comment]
Thank you for your thorough response! It is very clear to me now which test is used based on my input paramaters.
