### ISSUE TITLE
Extract NMIs

### ISSUE THREAD

**Issue by Denisesabac** [BRANCHlab/metasnf#9]
Hello! I have run the meta snf pipeline and was wondering if there is a way for me to view the NMI scores for each iteration. Thank you!

**Comment by pvelayudhan** [comment]
Hi, there currently isn't support for calculating NMI scores. If you want to understand the importance of your input features, you can use the `extend_solutions` function where you have your original data_list in place of the target list. This will calculate p-values relating all your input variables to your cluster solutions (where cluster is treated as a categorical predictor) and should achieve the same effect as the NMI calculations. 

The manhattan plot functionality and data calculations going into it may also be useful to check out: https://branchlab.github.io/metasnf/articles/manhattan_plots.html 

At the moment I do not have a good grasp on what information NMI calculations add that the simpler modeling does not.

**Comment by pvelayudhan** [comment]
Hi @Denisesabac, just sharing that NMI calculations are now possible as of v0.6.0. Vignette is here: https://branchlab.github.io/metasnf/articles/nmi_scores.html
